### ISSUE TITLE
Finish line tracker

### ISSUE THREAD

**Issue by RaitoBezarius** [nix-community/lanzaboote#9]
- [x] Proper name of the stub per generation, so it gets sorted WELL
- [x] Proper name for the initrd & kernel
- [ ] Bootspec for `/boot/EFI/nixos` place
- [x] Correct permissions for all files on ESP (a064f07a9dce65701d3945809b1f6cdef3cf34d2)
- [ ] Documentation on key rotation
- [x] Documentation on enrolling keys (simple scenarios)
- [x] Testing that initrd and kernel are signed (try to boot with an unsigned initrd or kernel and check that it fails): https://github.com/blitz/lanzaboote/pull/10/commits/b46e05d89b3a5d0dd187843a033326daeadd6989
- [x] Changing asciiart to correctly display "lanzaboote" (54112e99e907c5b2a9aafa7b048994959a488af9)
- [x] Display nice error messages when a file is not signed
- [ ] Management of "getting out of SB mode" and "re-entering SB mode" wrt to old generations and older loader files: #37 
- [ ] TPM event logging things & measurements in our stub
- [x] Sync the FAT32 writes
- [x] Specialisation is still working?
    - [x] Recursive signing of the specialisations files with lanzatool through bootspec

**Comment by RaitoBezarius** [comment]
### For TPM

we want to do it this way most likely: https://github.com/systemd/systemd/blob/main/src/boot/efi/stub.c#L185-L219 — but not so sure about those UEFI variables writes all the time

**Comment by RaitoBezarius** [comment]
### systemd-boot-builder style things

- [ ] Auto remove old entries which are not generations anymore
- [ ] Write specialisations entries
- [ ] Append initrd secrets

**Comment by RaitoBezarius** [comment]
- [ ] Respect `configurationLimit` for generations
   - [ ] Sorting issues

**Comment by RaitoBezarius** [comment]
- [ ] Support alternative locations for Nix stores (esp.rs stripping)

**Comment by RaitoBezarius** [comment]
- [ ] Patch the `os-release` to have a proper `PRETTY_NAME`

**Comment by RaitoBezarius** [comment]
- [ ] Bootspec seems to be missing or broken for specialisations

**Comment by blitz** [comment]
[ ] Embed SHA-256 (or something else) hash of kernel/initrd into lanzaboote to prevent people from mixing/matching signed kernels/initrds by swapping the files on the ESP. This would also remove the hack of wrapping the initrd into a PE binary.

**Comment by nikstur** [comment]
I do not believe that we want to auto-enroll keys on switch-to-configuration. Instead we should implement 'lanzatool rotate-keys' that generates a new bundle, re-signs all generations that could be verified with the old bundle, and enrolls the new bundle in the UEFI. We would need to make it reasonable safe so that no bad things happen in between these steps.

**Comment by RaitoBezarius** [comment]
> I do not believe that we want to auto-enroll keys on switch-to-configuration. Instead we should implement 'lanzatool rotate-keys' that generates a new bundle, re-signs all generations that could be verified with the old bundle, and enrolls the new bundle in the UEFI. We would need to make it reasonable safe so that no bad things happen in between these steps.

We can revisit this later, I agree with `lanzatool rotate-keys` as a necessary thing.

**Comment by RaitoBezarius** [comment]
- [ ] Sign from HSM / smartcards stuff (any PKCS#7 engine?)

**Comment by blitz** [comment]
- [ ] Timeouts on integration test failures. So far the CI will hang indefiniitely when `wait_for_console` in the NixOS integration test doesn't succeed.

**Comment by nikstur** [comment]
- [ ] A `--verbose` flag for lanzatool

**Comment by blitz** [comment]
> - [ ] A `--verbose` flag for lanzatool

I can look into that one. It's a good opportunity to use a logging library.

**Comment by RaitoBezarius** [comment]
- [ ] Option to test if current bootables will boot at all according to current keys (prevent frying your machine or forcing you to disable SB).
- [ ] https://github.com/nix-community/lanzaboote/issues/39

**Comment by blitz** [comment]
- [ ] Add lanzatool to nixpkgs
- [ ] Add lanzaboote to nixpkgs

**Comment by nikstur** [comment]
- [ ] Lanzatool: write loader.conf during install

**Comment by nikstur** [comment]
- [ ] Provide a way to update systemd-boot artifacts.

**Comment by nikstur** [comment]
- [ ] Bootspec field for `nixos-version`
- [ ] Bootspec field for kernel version

**Comment by nikstur** [comment]
- [ ] Change efivars when installing/updating via lanzatool

**Comment by blitz** [comment]
If we have things here that we really need to do before giving lanzaboote to users, we should create tickets and link them here: https://github.com/nix-community/lanzaboote/milestone/1

**Comment by nikstur** [comment]
Let's close this since we now have our [1.0 milestone](https://github.com/nix-community/lanzaboote/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+1.0.0%22).
